export const TXV_CONFIG = Object.freeze({
  defaultRefrigerant: 'R404A',
  defaultValve: 'T2_TE2',
  defaultTdK: 7.0,
  defaultTargetShK: 6.0,
  defaultEvapTempC: -27.0,
  defaultEvapPressureBarA: 2.22,
  defaultEvapPressureBarG: 1.21,
  defaultEvapPressureBar: 1.21,
  defaultSuctionTempC: -21.0,
  temperatureMinC: -80,
  temperatureMaxC: 100,
  pressureMinBar: 0,
  pressureMaxBar: 50,
  adjustmentToleranceK: 0.4,
  turnIncrement: 0.25,
  defaultMaxTurns: 5,
});
